const getters = {
  filterTagList: state => state.sideBar.filterTagList,
  selectAccountTagFilter: state => state.sideBar.selectTagFilter.account,
  selectQzglTagFilter: state => state.sideBar.selectTagFilter.qzgl,
  selectZyglTagFilter: state => state.sideBar.selectTagFilter.zygl,
  selectYceeTagFilter: state => state.sideBar.selectTagFilter.ycee,
  bindHintFlag: state => state.account.bindHintFlag,
  bindExecuteFlag: state => state.account.bindExecuteFlag,
  bqFlag: state => state.account.bqFlag,
  fenpFlag: state => state.account.fenpFlag,

  isAdmin: state => state.app.isAdmin,
  language: state => state.app.language,
  supportLanguage: state => state.app.supportLanguageList,
  theme: state => state.app.theme,
  supportTheme: state => state.app.supportThemeList,
  site: state => state.app.site,
  supportSite: state => state.app.supportSiteList,
  area: state => state.app.area,
  supportArea: state => state.app.supportAreaList,
  asyncTaskNum: state => state.app.asyncTaskNum,

  showExecute: state => state.app.showExecute,
  userInfo: state => state.user.info,
  userId: state => state.user.userId,
  username: state => state.user.username,
  useravatar: state => state.user.useravatar,
  token: state => state.user.token,
  role: state => state.user.role,
  userConfig: state => state.user.config,
  deptId: state => state.user.deptId,
  languageList: state => state.user.languageList,
  menu: state => state.menu.menu,
  routes: state => state.menu.routes,
  navbarList: state => state.menu.navbar,
  navbarShowList: state => state.menu.navbarIds,
  permission: state => state.user.permission,

  accountTableSidebar: state => state.accountTable.tagResult,

  selectAvatarTagFilter: state => state.sideBar.selectTagFilter.avatar,
  selectCoverTagFilter: state => state.sideBar.selectTagFilter.cover,
  selectbasicDataTagFilter: state => state.sideBar.selectTagFilter.basicData,
  selectFirstNameTagFilter: state => state.sideBar.selectTagFilter.firstName,
  selectLastNameTagFilter: state => state.sideBar.selectTagFilter.lastName,
  selectHomeTagFilter: state => state.sideBar.selectTagFilter.home,
  selectCityTagFilter: state => state.sideBar.selectTagFilter.city,
  selectUniversityFilter: state => state.sideBar.selectTagFilter.university,
  selectSchoolTagFilter: state => state.sideBar.selectTagFilter.school,
  selectWorkTagFilter: state => state.sideBar.selectTagFilter.work,
  selectEmailTagFilter: state => state.sideBar.selectTagFilter.email,
  selectPhoneTagFilter: state => state.sideBar.selectTagFilter.phone,
  selectZczlTagFilter: state => state.sideBar.selectTagFilter.zczl,

  chartViewData1: state => state.registTaskChat.chartViewData1,
  chartViewData2: state => state.registTaskChat.chartViewData2,
  chartViewData3: state => state.registTaskChat.chartViewData3,
  chartViewData4: state => state.registTaskChat.chartViewData4

}

export default getters
